### ISSUE TITLE
UI Improvements

### ISSUE THREAD

**Issue by cameronRomo** [cameronRomo/GameStack#10]
### Tasks:
* [x] Add dynamic header
* [x] Genres
  * [x] Fix genres with long text
  * [x] Render genre images as covers
  * [x] Add "Genres" header
* [x] Game Cards
  * [x] Move platforms and metacritic above the game name
  * [x] Add more spacing between cards
  * [x] Add an Emoji to represent the top rating
* [x] Ship Genres statically to reduce the number of loading spinners
* [x] Ship Platforms with the app to reduce calls to the server
* [x] Dark mode should be darker
